# Site settings
title: 万事屋
email: tcya24@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is tcya's personal blog.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://tcya.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  tcya

# Build settings
markdown: kramdown

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: 'page:num'

# Excerpt
excerpt_separator: '<!-- excerpt break -->'

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X

layout: default
comments: true
